[world]
description = "Empty PixeLAW world"
name = "myapp"
seed = "pixelaw"

[namespace]
default = "pixelaw"
mappings = {}

[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
keystore_path = "accounts/sepolia.deployer.keystore.json"
world_address = "0x6f130c8e150882e39cbe878c650c8f35c86579180dbc77d0c1cbe169449b5f6"

account_address = "YOUR_ACCOUNT"